= DSRT 2015
Makzan <mak@makzan.net>
v0.1, 2015-10-07









== Current status of Mobile web app
- Pure mobile web
- Expectation: app vs web
- Hybrid approach

=== Pure web app

Here you can find few examples on pure web app.

When the forecast.io debuts, it is called the best weather app that you won't find in the App Store.

PieGuy
forecast.io



=== Hybrid approach
Take the benefits of both app platform and web technology
Native part to gain native code performance and hardware access
Web technology for user interface creation
NOTE: app gesture and touch handling is better

== Case study—Basecamp for mobile

Pure server side render
Then client capture the request and create the iOS view hierarchy.
Navigation controller, push and pop Modal view controller
Then making some elements native, such as the menu.
Then, fine tuning the web for touch CSS
Then, moving more part that requires high performance info native.
It's a process. A transition. Won't archive it at one step.

== Case study—Facebook app
First 9 grid native app
Then list view
Then pure web view
Then rewrite into native app.

== Android JavaScript performance
Very poor.
iPhone 5 level

Expect it will be slow to run a heavy client side JavaScript framework in Android.

== PhoneGap Build
If you just need the web view wrapper.
Web based service
Paid service
Don't need to brother setting up the android and iOS platform
You may use PhoneGap build for your pure web app, even if you haven't used any PhoneGap functions.

== Mobile app layout in CSS

we need to learn some mobile styling technique to make our HTML-based web app works well in mobile defice with touch screen.

=== Flexbox approach
http://flexbox.website/chapter-1/flex-grow-and-shrink.html

=== Zurb Foundation for App
Build on AngularJS
Use Flexbox
It provides handy pre defined styles to make app layout. Also it uses Angular routing with their own front matter to create easy navigation.

TODO: Example of routing front matter here

=== Zurb Foundation 6
coming this december
TODO: link to the zurb foundation 6 blog post.

It's going to be the most advanced. CSS framework to date.

=== Bootstrap

Good for developers to build something quick without worrying about the styles. Also good for building internal app that doesn't need to face your customers.

=== Ionic Framework

Build on top of AngularJS
It's a trend now.
It uses hybrid approach

== Responsive Web

The same code can actually run on both mobile device and desktop.

=== Example—Fluid app

I actually wrap many of web services I use every day into desktop application by using an app called Fluid. I provide the URL to the Fluid app. Then It basically use a web view to load the URL in a separated app container. The result is I can have them in my dock for easy access.

=== Electron

There are more and more desktop apps now actually builds on top of the web technology. It uses a local NodeJS runtime to make use of the system resources where the web API won't provide because of the security reason.

Electron combines both advantages of web technology and the Node.js package ecosystem.

The large amount of Node.js packages and the system level API allows many possibilities. On the front end, the mature of web technology makes app designer easier to craft the interface and the view controllers.



=== Mobile first approach

we design on the mobile device first.





== Using map

- Google map
- MapBox
- OpenStreetMap

== Example—Rain or Not?



== Storage

Local storage and Remote storage

Possible remote storage option:

- Remote database with MongoDB service
- Remote database with Parse.com
- Remote database with Firebase


== Push Notification


== Making web app offline

There are two levels of caching things offline.

1. Storing the user data
2. Caching the files, including the HTML, CSS and JavaScript

The first one still needs Internet access to fetch the app files, which is the HTML, JavaScript logic and the CSS styles. The second one, cache these files as well to archive truly offline usage. You can even power on the iPhone in airplane mode and the web app still works without Internet.



== Offline example

In the colloid all, try to access them offline.

1. Go to the PieGuy web page in mobile Safari.
2. Add the PieGuy to home screen.
3. Open the PieGuy game once, with Internet access.
4. Take the phone offline by turning on airplane mode. You may even turn off the iPhone and turn it on again.
5. Launch the PieGuy game from home screens and the game should work without issues.


== AppCache





== Choosing framework to use

== Introducing jQuery mobile
the easiest way to make informative mobile web.

== Web app with ReactJS

== Building native app with ReactNative

ReactNative allows us to use the React philosophy to build the native view components.

== Server side pre-rendering React component

Why we need to pre render the React component?

That's for fallback for browsers that don't have JavaScript support.






== Distribution Channels

- Testing web app on devices in local network
- App distribution
- Distributing to the web
- Minify your code
- Adding the web app to iOS home screen
- Phonegap Build
- Publish to App Store
- Publish to Google Play
- Distribution is just the beginning
- Some more tips
