= DSRT 2015
Makzan <mak@makzan.net>
v0.1, 2015-10-07

This is the course material I created for the cross-platform development class. in this course, we will explore different approaches and choices to build app for different platforms, mainly iOS, Android and web.

== How this course is constructed

There are different individual topics that we are going to cover in this course. You can find the course entry point at http://page.sh/dsrt2015

The entry point provides the outline links to each individual topic. It also comes with a log to show the changes I have made from time to time. 

== About this course

In my part of the course, we focus on different web technologies to create mobile web app.

You'll need to know basic HTML, CSS, and Javascript.

We will also explore how we can make use of native platform resources to create hybrid app.

You can refer to my past course materials on makzan.net for some basic skills.

== What type of app you need to build?

Different types of apps requires different solutions which involves of different technologies. 

You need to learn the advantages of each technology and know where to use the right one for different situations. 

Roughly, we have the following common types of applications.

We explore several common types and see what technologies we shall use to make the app. 

* Informative app

One common type is informative app. That the app organize and display information in a easy to read hierarchy. 

* Utilities

Small utilities

* Productivity tools

* Photography

* Games

It depends. For serious game, obviously native gains the performance advantages. But for casual games, we can use canvas, webGL from HTML5 to build a smooth game. 

* e-book

The web is good for displaying interactive content. 

But be aware that if we need the 

* Music 

Web audio supports isn't really good. So native is really the technology we want to build music playback application. 

For example, we sure need the iOS native API to implement the background playback function to allow listening to the music when the phone is locked. 

But we actually can still make use of the web technologies somewhere. For example, we can build the interface in web view. There are connections between web and the native API. 

* Entertainment

== Why web technology?

Every device have a browser
* not all. Apple TV OS doesn't have WebKit component.

We are familiar with web technology:
HTML, CSS, JavaScript


== Current status of Mobile web app
- Pure mobile web
- Expectation: app vs web
- Hybrid approach

=== Pure web app

Here you can find few examples on pure web app.

When the forecast.io debuts, it is called the best weather app that you won't find in the App Store.

PieGuy
forecast.io

== Expectation: App vs web

.App
- Get things done
- Usability
- Platform specific
- Device hardware
- Default offline

.Web
- Informative
- Hierarchy
- Readability
- Deep linking

You won’t think that a website works in iPhone but not android. But you will find apps working on 1 platform only. Also, you think you can use any device to see the website and get what information you want


=== Web for app?
In my opinions, we will never archive app experience with web technology. That's same that we will never archive web’s culture with app technology.
They are different things. They are designed for different purposes.
But, we can combine both by taking their advantages and avoiding their weaknesses.

=== The process of building native app vs web app

the graph

Using the pure web technology to build app is fast.

Using native technology to build app seemed to eb slow, but in the long run, it has more stable curve.

=== Hybrid approach
Take the benefits of both app platform and web technology
Native part to gain native code performance and hardware access
Web technology for user interface creation
NOTE: app gesture and touch handling is better

== Case study—Basecamp for mobile

Pure server side render
Then client capture the request and create the iOS view hierarchy.
Navigation controller, push and pop Modal view controller
Then making some elements native, such as the menu.
Then, fine tuning the web for touch CSS
Then, moving more part that requires high performance info native.
It's a process. A transition. Won't archive it at one step.

== Case study—Facebook app
First 9 grid native app
Then list view
Then pure web view
Then rewrite into native app.

== Android JavaScript performance
Very poor.
iPhone 5 level

Expect it will be slow to run a heavy client side JavaScript framework in Android.

== PhoneGap Build
If you just need the web view wrapper.
Web based service
Paid service
Don't need to brother setting up the android and iOS platform
You may use PhoneGap build for your pure web app, even if you haven't used any PhoneGap functions.

== Mobile app layout in CSS

we need to learn some mobile styling technique to make our HTML-based web app works well in mobile defice with touch screen.

=== Flexbox approach
http://flexbox.website/chapter-1/flex-grow-and-shrink.html

=== Zurb Foundation for App
Build on AngularJS
Use Flexbox
It provides handy pre defined styles to make app layout. Also it uses Angular routing with their own front matter to create easy navigation.

TODO: Example of routing front matter here

=== Zurb Foundation 6
coming this december
TODO: link to the zurb foundation 6 blog post.

It's going to be the most advanced. CSS framework to date.

=== Bootstrap

Good for developers to build something quick without worrying about the styles. Also good for building internal app that doesn't need to face your customers.

=== Ionic Framework

Build on top of AngularJS
It's a trend now.
It uses hybrid approach

== Responsive Web

The same code can actually run on both mobile device and desktop.

=== Example—Fluid app

I actually wrap many of web services I use every day into desktop application by using an app called Fluid. I provide the URL to the Fluid app. Then It basically use a web view to load the URL in a separated app container. The result is I can have them in my dock for easy access.

=== Electron

There are more and more desktop apps now actually builds on top of the web technology. It uses a local NodeJS runtime to make use of the system resources where the web API won't provide because of the security reason.

Electron combines both advantages of web technology and the Node.js package ecosystem.

The large amount of Node.js packages and the system level API allows many possibilities. On the front end, the mature of web technology makes app designer easier to craft the interface and the view controllers.



=== Mobile first approach

we design on the mobile device first.



== Getting device information in web

Getting accelerometer

Getting orientation

Getting gyroscope

Accepting photo upload

=== Getting orientation

=== Getting Gyroscope & Accelerometer

Getting raw data

[source,javascript]
----
window.addEventListener('devicemotion', function (e) {
  this.acceleration = e.acceleration;
};
----

==== The code example

We use a list to display the value history.

[source,html]
----
<ul id="x" class="history">
  <li>No Data Yet</li>
</ul>
----

We use an array to store the history of the value. And set a limit count to the array.

[source,javascript]
----
app.xValues = [];
window.addEventListener('devicemotion', function (e) {
  app.xValues.push(e.acceleration.x);
  var listLimit = 15;
  if (app.xValues.length > listLimit) {
    app.xValues.splice(0, 1); // remove the old records when list too long.
  }

  app.view.update();
});
----

[source,javascript]
----
app.view = {}
app.view.update = function(){
  this.renderHistory($('#x'), app.xValues);
}

app.view.renderHistory = function(element, data) {
  $(element).empty();
  for (var i = app.xValues.length - 1; i >= 0; i--) {
    $(element).append("<li>" + Math.floor(data[i]*1000) + "</li>");
  };
}
----

Note that this code only shows the handling of X value. There are Y and Z value in accelerometer sensor that share very similar logic.

=== Visualize the accelerometer value history a pie chart

We will put a canvas in each axis.

[source,html]
----
<div class='row'>
  <h2>X</h2>
  <canvas id='x-canvas' width='80' height='40'></canvas>
  <ul id='x' class='history'>
    <li>No Data Yet</li>
  </ul>
</div>
----

We will use a graph to show the historical values of the sensor.

[source,javascript]
----
// Graph
(function(){
  var app = this.app || (this.app={});

  // A bar chart for - Max Value to + Max Value.
  app.Graph = (function(){
    function Graph(canvasId, maxValue){
      this.canvas = document.getElementById(canvasId);
      if (this.canvas) {
        this.context = this.canvas.getContext('2d');
      }

      // set the Y unit scale.
      this.unit = this.canvas.height / 2 / maxValue; // divide by 2 because half for + and half for -.
    }
    Graph.prototype.drawBar = function(x, value) {
      var c = this.context;
      c.beginPath();
      c.moveTo(x, this.canvas.height/2); // middle
      c.lineTo(x, this.canvas.height/2 - value * this.unit);
      c.lineWidth = 3;
      c.strokeStyle = "#222";
      c.stroke();
      c.closePath();
    };
    Graph.prototype.render = function(dataArray) {
      this.canvas.width = this.canvas.width;
      for (var i=0, len=dataArray.length; i<len; i++) {
        this.drawBar(i*5, dataArray[i]);
      }
    }
    return Graph;
  })();
}).call(this);
----

At last, we use the Graph to render the historical data.

[source,javascript]
----
var graphX = new app.Graph('x-canvas', 2.5);
graphX.render(app.xValues);
----

=== Inspecting the gyroscope sensor

You can test the app here: http://mztests.herokuapp.com/rotation/

The different is just change to listen to `deviceorientation` and use `e.alpha`, `e.beta`, `e.gamma` for the rotation axises.

[source,javascript]
----
window.addEventListener('deviceorientation', function (e) {
  app.xValues.push(e.alpha);
  app.yValues.push(e.beta);
  app.zValues.push(e.gamma);
  // ... code that is very similar to the accelerometer section.
}
----

== Using map

- Google map
- MapBox
- OpenStreetMap

== Example—Rain or Not?



== Storage

Local storage and Remote storage

Possible remote storage option:

- Remote database with MongoDB service
- Remote database with Parse.com
- Remote database with Firebase


== Push Notification


== Making web app offline

There are two levels of caching things offline.

1. Storing the user data
2. Caching the files, including the HTML, CSS and JavaScript

The first one still needs Internet access to fetch the app files, which is the HTML, JavaScript logic and the CSS styles. The second one, cache these files as well to archive truly offline usage. You can even power on the iPhone in airplane mode and the web app still works without Internet.



== Offline example

In the colloid all, try to access them offline.

1. Go to the PieGuy web page in mobile Safari.
2. Add the PieGuy to home screen.
3. Open the PieGuy game once, with Internet access.
4. Take the phone offline by turning on airplane mode. You may even turn off the iPhone and turn it on again.
5. Launch the PieGuy game from home screens and the game should work without issues.


== AppCache



== Mobile navigation

=== Navigation difference between platform
The difference is huge
Windows, Android, iOS
It's not about the style (skepticism or "flat", or depth)
It's about the user habits.
It's about the strategy (tabs on bottom, tabs at top, infinite canvas)
It's about the hardware buttons that affects the software design

=== Hamburger menu?
Conclusion: avoid it.
At least don't just put the hamburger menu there.

== Case study navigation—Facebook
First 9 grid
Then list view
Then hamburger menu
Then double hamburger menu
Then removed main hamburger menu and back to tab

== Choosing framework to use

== Introducing jQuery mobile
the easiest way to make informative mobile web.

== Web app with ReactJS

== Building native app with ReactNative

ReactNative allows us to use the React philosophy to build the native view components.

== Server side pre-rendering React component

Why we need to pre render the React component?

That's for fallback for browsers that don't have JavaScript support.

== Accessibility—Making the web inclusive

One difference between web and app is that web pages should be designed to be inclusive. It doesn't and never lock into perticular platform. It's designed so that every one can get the information. This is why we need to handle accessibility in our web pages.

== ARIA roles

=== Common ARIA Roles

- For structure
- For buttons
- For UI Components

=== UI Components

- Dialog
- Tab and Tabs Content

== Color blind




== Distribution Channels

- Testing web app on devices in local network
- App distribution
- Distributing to the web
- Minify your code
- Adding the web app to iOS home screen
- Phonegap Build
- Publish to App Store
- Publish to Google Play
- Distribution is just the beginning
- Some more tips
