== What type of app you need to build?

Different types of apps requires different solutions which involves of different technologies. You need to learn the advantages of each technology and know where to use the right one for different situations.

Roughly, we have the following common types of applications.

We explore several common types and see what technologies we shall use to make the app.

* Informative app

One common type is informative app. That the app organize and display information in a easy to read hierarchy.

* Utilities

Small utilities

Such as:

- Rulers
- Currency converter
- Weather utility

* compare to the weather full feature app

Tiny tools that does one thing great.

* Productivity tools

An entire suite of application, such as Microsoft Office, iWorks.

* Photography

Usually it needs to be native to access the camera stream.

In web, we often only have access to a taken photo instead of getting the real time camera data.

But actually it depends on what the photography app we want to build.

// For example, the Funny Face project only needs a taken photo and add fun faces on it. In real world example, it would be the Minions promotion website.

* Games

It depends. For serious game, obviously native gains the performance advantages. But for casual games, we can use canvas, webGL from HTML5 to build a smooth game.

* e-book

The web is good for displaying interactive content.

But be aware that if we need the touch and gesture, we may need to carefully craft the touch/gesture experience. It's not as easy as in native environment.

* Music

Web audio supports isn't really good. So native is really the technology we want to build music playback application.

For example, we sure need the iOS native API to implement the background playback function to allow listening to the music when the phone is locked.

But we actually can still make use of the web technologies somewhere. For example, we can build the interface in web view. There are connections between web and the native API.

// * Entertainment


More on: http://www.makzan.net/mobile-web-app-dev-with-phonegap/app-categories/[App Categories]
