== Expectation: App vs web

There is different expectations between using an app and browsing a web site.

.App
- Get things done
- Usability
- Platform specific
- Device hardware
- Default offline

.Web
- Informative
- Hierarchy
- Readability
- Deep linking

You will find apps working on 1 platform only, at most 2 platforms. But you won’t expect a website that works in iPhone and work in Android. We expect that we can use any device to see the website and get what information you want


=== Web for app?
In my opinions, we will never archive app experience with web technology. That's same that we will never archive web’s culture with app technology.
They are different things. They are designed for different purposes.
But, we can combine both by taking their advantages and avoiding their weaknesses.

=== The process of building native app vs web app

TODO: the graph

Using the pure web technology to build app is fast.

Using native technology to build app seemed to eb slow, but in the long run, it has more stable curve.

***

Actually there is no such thing about app must win or web must win. They can both win in their places and be campanion to each other.
