= DSRT 2015
Makzan <mak@makzan.net>
v0.3, 2015-10-16

This is an introduction course. We focus on how things should work. We won't learns a lot of in depth coding skill. But you need to know what is good enough , what is great and what is bad.


== How fast your web application loads

When using web technologies to create application, one key thing to make the web page really like an application is to remove the response time. This includes the response of the buttons tapping or using the interface. It also includes the loading time of the web page.

https://speakerdeck.com/addyosmani/whats-new-in-chrome-devtools

== distribution channels

* PhoneGap build
* Xcodd with web view
* android studio with web view
* CocoonJS

== making the user interface like app

* Touch and click delay
* CSS framework
** Ionic
**
* jQuery mobile
Flexbox layout

Tips: if you want to reuse the interface in cross platform, don't make it look like one platform. Don't make it look like iOS or android.

So when you choose what CSS framework to use, avoid those that mimic the iOS or android.

== Books to read and learn

Js recommend book:
JavaScript the good part
Learn ES6



== PhoneGap Build
If you just need the web view wrapper.
Web based service
Paid service
Don't need to brother setting up the android and iOS platform
You may use PhoneGap build for your pure web app, even if you haven't used any PhoneGap functions.

== Mobile app layout in CSS

we need to learn some mobile styling technique to make our HTML-based web app works well in mobile defice with touch screen.

=== Flexbox approach
http://flexbox.website/chapter-1/flex-grow-and-shrink.html

=== Zurb Foundation for App
Build on AngularJS
Use Flexbox
It provides handy pre defined styles to make app layout. Also it uses Angular routing with their own front matter to create easy navigation.

TODO: Example of routing front matter here

=== Zurb Foundation 6
coming this december
TODO: link to the zurb foundation 6 blog post.

It's going to be the most advanced. CSS framework to date.

=== Bootstrap

Good for developers to build something quick without worrying about the styles. Also good for building internal app that doesn't need to face your customers.

=== Ionic Framework

Build on top of AngularJS
It's a trend now.
It uses hybrid approach

== Responsive Web

The same code can actually run on both mobile device and desktop.





=== Mobile first approach

we design on the mobile device first.



== Using map

- Google map
- MapBox
- OpenStreetMap



== Push Notification





== Choosing framework to use

== Introducing jQuery mobile
the easiest way to make informative mobile web.

== Web app with ReactJS

== Building native app with ReactNative

ReactNative allows us to use the React philosophy to build the native view components.





== Distribution Channels

- Testing web app on devices in local network
- App distribution
- Distributing to the web
- Minify your code
- Adding the web app to iOS home screen
- PhoneGap Build
- Publish to App Store
- Publish to Google Play
- Distribution is just the beginning
- Some more tips
