= DSRT 2015
Makzan <mak@makzan.net>
v0.2, 2015-10-08

This is an introduction course. We focus on how things should work. We won't learns a lot of in depth coding skill. But you need to know what is good enough , what is great and what is bad.




== Books to read and learn

Js recommend book:
JavaScript the good part
Learn ES6



== PhoneGap Build
If you just need the web view wrapper.
Web based service
Paid service
Don't need to brother setting up the android and iOS platform
You may use PhoneGap build for your pure web app, even if you haven't used any PhoneGap functions.

== Mobile app layout in CSS

we need to learn some mobile styling technique to make our HTML-based web app works well in mobile defice with touch screen.

=== Flexbox approach
http://flexbox.website/chapter-1/flex-grow-and-shrink.html

=== Zurb Foundation for App
Build on AngularJS
Use Flexbox
It provides handy pre defined styles to make app layout. Also it uses Angular routing with their own front matter to create easy navigation.

TODO: Example of routing front matter here

=== Zurb Foundation 6
coming this december
TODO: link to the zurb foundation 6 blog post.

It's going to be the most advanced. CSS framework to date.

=== Bootstrap

Good for developers to build something quick without worrying about the styles. Also good for building internal app that doesn't need to face your customers.

=== Ionic Framework

Build on top of AngularJS
It's a trend now.
It uses hybrid approach

== Responsive Web

The same code can actually run on both mobile device and desktop.





=== Mobile first approach

we design on the mobile device first.



== Using map

- Google map
- MapBox
- OpenStreetMap



== Storage

Local storage and Remote storage

Possible remote storage option:

- Remote database with MongoDB service
- Remote database with Parse.com
- Remote database with Firebase


== Push Notification





== Choosing framework to use

== Introducing jQuery mobile
the easiest way to make informative mobile web.

== Web app with ReactJS

== Building native app with ReactNative

ReactNative allows us to use the React philosophy to build the native view components.





== Distribution Channels

- Testing web app on devices in local network
- App distribution
- Distributing to the web
- Minify your code
- Adding the web app to iOS home screen
- Phonegap Build
- Publish to App Store
- Publish to Google Play
- Distribution is just the beginning
- Some more tips
